<?php

namespace OctopusPress\Bundle\Tests\Model;

use OctopusPress\Bundle\Model\ThemeManager;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ThemeManagerTest extends KernelTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::bootKernel();
    }

    /**
     * @throws \Psr\Container\ContainerExceptionInterface
     * @throws \Psr\Container\NotFoundExceptionInterface
     */
    public function testActivate()
    {
        $container = static::getContainer();

        /**
         * @var $manager ThemeManager
         */
        $manager = $container->get(ThemeManager::class);

        $manager->activate('default');

        $this->assertDirectoryExists($manager->targetDir('default'));
    }

    public function testInactivation()
    {
        $container = static::getContainer();

        /**
         * @var $manager ThemeManager
         */
        $manager = $container->get(ThemeManager::class);

        $manager->deactivate('default');

        $this->assertDirectoryDoesNotExist($manager->targetDir('default'));
    }
}
