<?php

namespace OctopusPress\Bundle;

use OctopusPress\Bundle\DependencyInjection\Compiler\LastExecutionPass;
use OctopusPress\Bundle\DependencyInjection\Compiler\TwigPass;
use OctopusPress\Bundle\DependencyInjection\OctopusPressExtension;
use Symfony\Component\DependencyInjection\Compiler\PassConfig;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Extension\ExtensionInterface;
use Symfony\Component\HttpKernel\Bundle\AbstractBundle;

class OctopusPressBundle extends AbstractBundle
{
    public function boot()
    {
        // TODO: Change the autogenerated stub

    }

    public function build(ContainerBuilder $container): void
    {
        // TODO: Change the autogenerated stub
        parent::build($container);
        if ($container->hasExtension('twig')) {
            $container->addCompilerPass(new TwigPass());
        }
        $container->addCompilerPass(new LastExecutionPass(), PassConfig::TYPE_BEFORE_REMOVING);
    }


    public function getContainerExtension(): ?ExtensionInterface
    {
        return new OctopusPressExtension();
    }

    public function getPath(): string
    {
        return \dirname(__DIR__);
    }
}
